# =============================================================================
# MRC VR Website Deployment Script
# =============================================================================
# This script helps deploy the Quarto website to GitHub Pages
#
# Usage:
#   source("deploy.R")
#   deploy()                    # Full deployment (render + commit + push)
#   deploy(render = FALSE)      # Skip rendering, just commit and push
#   deploy(push = FALSE)        # Render and commit, but don't push
#   setup_github()              # First-time GitHub setup
# =============================================================================

library(glue)

# Configuration - UPDATE THESE VALUES
GITHUB_USERNAME <- "bridaybrummer"  # Your GitHub username
REPO_NAME <- "MRC_VR"               # Repository name
DEFAULT_BRANCH <- "main"            # or "master"

# =============================================================================
# Helper Functions
# =============================================================================

msg <- function(..., type = "info") {
  prefix <- switch(type,
    "info"    = "\033[32m✓\033[0m",
    "warning" = "\033[33m⚠\033[0m", 
    "error"   = "\033[31m✗\033[0m",
    "step"    = "\033[34m→\033[0m",
    ""

)
  message(prefix, " ", ...)
}

run_cmd <- function(cmd, echo = TRUE) {
  if (echo) msg(cmd, type = "step")
  result <- system(cmd, intern = TRUE)
  if (!is.null(attr(result, "status")) && attr(result, "status") != 0) {
    msg("Command failed: ", cmd, type = "error")
    return(NULL)
  }
  return(result)
}

check_command <- function(cmd) {
  result <- suppressWarnings(system(paste("which", cmd), intern = TRUE, ignore.stderr = TRUE))
  return(length(result) > 0 && nchar(result[1]) > 0)
}

# =============================================================================
# Check Prerequisites
# =============================================================================

check_prerequisites <- function() {
  msg("Checking prerequisites...", type = "step")
  
  checks <- list(
    git = check_command("git"),
    quarto = check_command("quarto"),
    r = TRUE
  )
  
  if (!checks$git) {
    msg("Git is not installed. Please install Git first.", type = "error")
    return(FALSE)
  }
  msg("Git found")
  

  if (!checks$quarto) {
    msg("Quarto is not installed. Please install Quarto first.", type = "error
")
    msg("Download from: https://quarto.org/docs/get-started/", type = "info")
    return(FALSE)
  }
  msg("Quarto found")
  
  # Check if we're in the right directory
  if (!file.exists("_quarto.yml")) {
    msg("_quarto.yml not found. Are you in the MRC_VR directory?", type = "error")
    return(FALSE)
  }
  msg("Quarto project found")
  
  return(TRUE)
}

# =============================================================================
# Setup .gitignore
# =============================================================================

setup_gitignore <- function() {
  msg("Setting up .gitignore...", type = "step")
  
  gitignore_content <- '# =============================================================================
# MRC VR .gitignore
# =============================================================================

# Data files (too large for git)
*.dta
*.feather
*.rda
*.rds
*.RData
*.xlsx
*.zip

# Rendered outputs (regenerated by quarto render)
# Keep docs/ for GitHub Pages
*.html
!docs/**/*.html
*.pdf
*.docx
~$*.docx
Rplots.pdf
index-listing.json

# Quarto intermediates
_freeze/
.quarto/
*_files/
site_libs/

# IDE and system
.DS_Store
.Rhistory
.RData
.Rproj.user/
.vscode/

# Standalone files not part of website
Diabetes.qmd
ICC_for_eMCCD_pilot*
ME_dashboard.qmd
ME_dashboard.html
ME_dashboard/
ME_dashboard_files/
j_code_modelling.qmd
j_code_modelling.html
j_code_modelling.bib
j_code_modelling*.docx
plot_dha_offices.qmd
plot_dha_offices.html
plot_dha_offices_files/

# Misc
wetransfer_*.zip
icc_outputs/
icd_code_map/
j_code/
confidence_interval_modelling/
figures/
'
  
  writeLines(gitignore_content, ".gitignore")
  msg(".gitignore updated")
}

# =============================================================================
# Initialize Git Repository
# =============================================================================

init_git <- function() {
  msg("Initializing Git repository...", type = "step")
  
  # Check if already a git repo
  if (dir.exists(".git")) {
    msg("Git repository already exists")
    return(TRUE)
  }
  
  run_cmd("git init")
  msg("Git repository initialized")
  return(TRUE)
}

# =============================================================================
# First-time GitHub Setup
# =============================================================================

setup_github <- function(username = GITHUB_USERNAME, repo = REPO_NAME) {
  msg("=== GitHub Setup ===", type = "step")
  
  if (!check_prerequisites()) return(invisible(FALSE))
  
  # Setup .gitignore
  setup_gitignore()
  
  # Initialize git
  init_git()
  
  # Check if remote exists
  remotes <- run_cmd("git remote -v", echo = FALSE)
  has_origin <- any(grepl("origin", remotes))
  
  if (!has_origin) {
    msg("Adding GitHub remote...", type = "step")
    remote_url <- glue("https://github.com/{username}/{repo}.git")
    run_cmd(glue('git remote add origin {remote_url}'))
    msg(glue("Remote added: {remote_url}"))
  } else {
    msg("Remote 'origin' already configured")
  }
  
  # Update README with correct username
  if (file.exists("README.md")) {
    readme <- readLines("README.md")
    readme <- gsub("YOUR_USERNAME", username, readme)
    writeLines(readme, "README.md")
    msg("README.md updated with your username")
  }
  
  # Update about.qmd with correct username
  if (file.exists("about.qmd")) {
    about <- readLines("about.qmd")
    about <- gsub("YOUR_USERNAME", username, about)
    writeLines(about, "about.qmd")
    msg("about.qmd updated with your username")
  }
  
  # Update _quarto.yml with correct username
  if (file.exists("_quarto.yml")) {
    quarto_yml <- readLines("_quarto.yml")
    quarto_yml <- gsub("YOUR_USERNAME", username, quarto_yml)
    writeLines(quarto_yml, "_quarto.yml")
    msg("_quarto.yml updated with your username")
  }
  
  cat("\n")
  msg("=== Setup Complete ===", type = "info")
  cat("\n")
  msg("Next steps:", type = "info")
  cat("
1. Create a new repository on GitHub:
   https://github.com/new
   
   Name: ", repo, "
   Do NOT initialize with README (you already have one)

2. Run the deployment:
   deploy()

3. Enable GitHub Pages:
   - Go to: https://github.com/", username, "/", repo, "/settings/pages
   - Source: Deploy from a branch
   - Branch: ", DEFAULT_BRANCH, "
   - Folder: /docs
   - Click Save

4. Your site will be live at:
   https://", username, ".github.io/", repo, "/
", sep = "")
  
  return(invisible(TRUE))
}

# =============================================================================
# Render Website
# =============================================================================

render_site <- function() {
  msg("Rendering Quarto website...", type = "step")
  
  result <- system("quarto render", intern = FALSE)
  
  if (result != 0) {
    msg("Quarto render failed!", type = "error")
    return(FALSE)
  }
  
  # Check if docs/ was created

  if (!dir.exists("docs")) {
    msg("docs/ directory not created. Check _quarto.yml output-dir setting.", type = "error")
    return(FALSE)
  }
  
  msg("Website rendered to docs/")
  return(TRUE)
}

# =============================================================================
# Commit Changes
# =============================================================================

commit_changes <- function(message = NULL) {
  msg("Committing changes...", type = "step")
  
  # Generate commit message if not provided
  if (is.null(message)) {
    message <- paste("Update website -", format(Sys.time(), "%Y-%m-%d %H:%M"))
  }
  
  # Stage all changes
  run_cmd("git add -A")
  
  # Check if there are changes to commit
  status <- run_cmd("git status --porcelain", echo = FALSE)
  if (length(status) == 0 || all(status == "")) {
    msg("No changes to commit")
    return(TRUE)
  }
  
  # Commit
  run_cmd(glue('git commit -m "{message}"'))
  msg(glue("Changes committed: {message}"))
  
  return(TRUE)
}

# =============================================================================
# Push to GitHub
# =============================================================================

push_to_github <- function(branch = DEFAULT_BRANCH) {
  msg("Pushing to GitHub...", type = "step")
  
  # Check if branch exists
  branches <- run_cmd("git branch", echo = FALSE)
  current_branch <- gsub("^\\* ", "", branches[grepl("^\\*", branches)])
  
  if (length(current_branch) == 0 || current_branch == "") {
    # No commits yet, need to make initial commit first
    msg("Creating initial commit...", type = "step")
    run_cmd("git add -A")
    run_cmd('git commit -m "Initial commit"')
    run_cmd(glue("git branch -M {branch}"))
  }
  
  # Push
  result <- system(glue("git push -u origin {branch}"), intern = FALSE)
  
  if (result != 0) {
    msg("Push failed. You may need to:", type = "warning")
    cat("
  1. Create the repository on GitHub first
  2. Check your GitHub authentication
  3. Try: git push -u origin ", branch, " --force (if this is a new repo)
", sep = "")
    return(FALSE)
  }
  
  msg("Successfully pushed to GitHub!")
  return(TRUE)
}

# =============================================================================
# Main Deploy Function
# =============================================================================

deploy <- function(render = TRUE, commit = TRUE, push = TRUE, 
                   message = NULL, branch = DEFAULT_BRANCH) {
  
  cat("\n")
  msg("=== MRC VR Website Deployment ===", type = "step")
  cat("\n")
  
  # Check prerequisites
  if (!check_prerequisites()) {
    return(invisible(FALSE))
  }
  
  # Render
  if (render) {
    if (!render_site()) {
      return(invisible(FALSE))
    }
  } else {
    msg("Skipping render", type = "warning")
  }
  
  # Commit
  if (commit) {
    if (!commit_changes(message)) {
      return(invisible(FALSE))
    }
  } else {
    msg("Skipping commit", type = "warning")
  }
  
  # Push
  if (push) {
    if (!push_to_github(branch)) {
      return(invisible(FALSE))
    }
  } else {
    msg("Skipping push", type = "warning")
  }
  
  cat("\n")
  msg("=== Deployment Complete ===", type = "info")
  
  if (push && GITHUB_USERNAME != "YOUR_USERNAME") {
    cat("\n")
    msg(glue("Site will be live at: https://{GITHUB_USERNAME}.github.io/{REPO_NAME}/"), type = "info")
    cat("\n")
  }
  
  return(invisible(TRUE))
}

# =============================================================================
# Status Check
# =============================================================================

status <- function() {
  msg("=== Repository Status ===", type = "step")
  cat("\n")
  
  # Git status
  if (dir.exists(".git")) {
    msg("Git repository: Yes")
    
    # Check remote
    remotes <- run_cmd("git remote -v", echo = FALSE)
    if (length(remotes) > 0 && any(nchar(remotes) > 0)) {
      msg(glue("Remote: {remotes[1]}"))
    } else {
      msg("Remote: Not configured", type = "warning")
    }
    
    # Check branch
    branch <- run_cmd("git branch --show-current", echo = FALSE)
    if (length(branch) > 0) msg(glue("Branch: {branch}"))
    
    # Check status
    changes <- run_cmd("git status --porcelain", echo = FALSE)
    if (length(changes) == 0 || all(changes == "")) {
      msg("Working tree: Clean")
    } else {
      msg(glue("Working tree: {length(changes)} changes pending"), type = "warning")
    }
  } else {
    msg("Git repository: Not initialized", type = "warning")
  }
  
  # Docs folder
  if (dir.exists("docs")) {
    n_files <- length(list.files("docs", recursive = TRUE))
    msg(glue("docs/ folder: {n_files} files"))
  } else {
    msg("docs/ folder: Not found (run quarto render)", type = "warning")
  }
  
  cat("\n")
}

# =============================================================================
# Print Usage on Source
# =============================================================================

cat("
╔══════════════════════════════════════════════════════════════════════════════╗
║                    MRC VR Website Deployment Script                          ║
╠══════════════════════════════════════════════════════════════════════════════╣
║                                                                              ║
║  FIRST TIME SETUP:                                                           ║
║    1. Edit GITHUB_USERNAME at the top of this file                           ║
║    2. Run: setup_github()                                                    ║
║    3. Create repo on GitHub, then run: deploy()                              ║
║                                                                              ║
║  COMMANDS:                                                                   ║
║    setup_github()        - First-time GitHub setup                           ║
║    deploy()              - Full deployment (render + commit + push)          ║
║    deploy(render=FALSE)  - Commit and push without re-rendering              ║
║    deploy(push=FALSE)    - Render and commit locally only                    ║
║    status()              - Check repository status                           ║
║                                                                              ║
╚══════════════════════════════════════════════════════════════════════════════╝
")
