<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-06-16">
<meta name="description" content="Data-quality assessment of the Part I cause lines and the derived underlying cause in the Isibalo/MACOD microdata, using the Free State province as a worked example, with implications for automated coding (IRIS / DoRIS).">

<title>Free State Cause-of-Death Coding Quality – MRC Vital Registration Analysis</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-a06763021a52c43c40a351ac8b799b8f.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-8abf46cc58cbf381e82762a1ae0d2821.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">MRC Vital Registration Analysis</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-projects" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Projects</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-projects">    
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../projects/mortality_estimates/index.html">
 <span class="dropdown-text">Monitoring &amp; Evaluation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../projects/national_overview/index.html">
 <span class="dropdown-text">National Excess Mortality</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../projects/cause_codes/index.html">
 <span class="dropdown-text">Cause Code Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../projects/free_state_cause_quality/index.html">
 <span class="dropdown-text">Free State Cause Quality</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../projects/dha_access/index.html">
 <span class="dropdown-text">DHA Access</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../projects/dha_access/methodology.html">
 <span class="dropdown-text">↳ Methodology (Method 3)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../projects/dha_access/methods_comparison.html">
 <span class="dropdown-text">↳ Methods comparison</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../projects/dha_access/sensitivity.html">
 <span class="dropdown-text">↳ Sensitivity: 500 m density</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../projects/dha_access/death_registration.html">
 <span class="dropdown-text">↳ Death registration</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../projects/dha_access/birth_registration.html">
 <span class="dropdown-text">↳ Birth registration</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../projects/icc_analysis/index.html">
 <span class="dropdown-text">ICC for eMCCD</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../projects/j_code_modelling/index.html">
 <span class="dropdown-text">J-Code Modelling</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../projects/signal_detection/index.html">
 <span class="dropdown-text">Signal Detection</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../projects/heat_excess_mortality/index.html">
 <span class="dropdown-text">Heat &amp; Excess Mortality</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../projects/poisoning_deaths/index.html">
 <span class="dropdown-text">Poisoning Deaths</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../projects/ci_modelling/index.html">
 <span class="dropdown-text">CI Modelling Methods</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../projects/CODe_correct_public/index.html">
 <span class="dropdown-text">CODe Correct lite app — Concept Note</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../projects/dhis_hospital_mortality/index.html">
 <span class="dropdown-text">DHIS2 Hospital Indicators</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../projects/data_explorer/index.html">
 <span class="dropdown-text">🔍 Data Explorer (Shiny)</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/bridaybrummer/MRC_VR"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Free State Cause-of-Death Coding Quality</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#why-this-matters" id="toc-why-this-matters" class="nav-link active" data-scroll-target="#why-this-matters"><span class="header-section-number">1</span> Why this matters</a></li>
  <li><a href="#completeness-of-the-cause-ad-lines" id="toc-completeness-of-the-cause-ad-lines" class="nav-link" data-scroll-target="#completeness-of-the-cause-ad-lines"><span class="header-section-number">2</span> 1. Completeness of the Cause A–D lines</a></li>
  <li><a href="#multiple-cause-depth-how-rich-is-the-certification" id="toc-multiple-cause-depth-how-rich-is-the-certification" class="nav-link" data-scroll-target="#multiple-cause-depth-how-rich-is-the-certification"><span class="header-section-number">3</span> 2. Multiple-cause depth (how rich is the certification?)</a></li>
  <li><a href="#cause-a-vs-the-underlying-cause-the-structural-break" id="toc-cause-a-vs-the-underlying-cause-the-structural-break" class="nav-link" data-scroll-target="#cause-a-vs-the-underlying-cause-the-structural-break"><span class="header-section-number">4</span> 3. Cause A vs the underlying cause — the structural break</a></li>
  <li><a href="#which-line-of-the-chain-does-the-ucod-come-from" id="toc-which-line-of-the-chain-does-the-ucod-come-from" class="nav-link" data-scroll-target="#which-line-of-the-chain-does-the-ucod-come-from"><span class="header-section-number">5</span> 4. Which line of the chain does the UCoD come from?</a></li>
  <li><a href="#ill-defined-and-garbage-underlying-causes-who-lens" id="toc-ill-defined-and-garbage-underlying-causes-who-lens" class="nav-link" data-scroll-target="#ill-defined-and-garbage-underlying-causes-who-lens"><span class="header-section-number">6</span> 5. Ill-defined and “garbage” underlying causes (WHO lens)</a></li>
  <li><a href="#three-ways-to-pick-the-tabulation-cause-which-is-cleanest" id="toc-three-ways-to-pick-the-tabulation-cause-which-is-cleanest" class="nav-link" data-scroll-target="#three-ways-to-pick-the-tabulation-cause-which-is-cleanest"><span class="header-section-number">7</span> 6. Three ways to pick the tabulation cause — which is cleanest?</a></li>
  <li><a href="#worked-rejections-when-a-better-ucod-beats-the-line-written" id="toc-worked-rejections-when-a-better-ucod-beats-the-line-written" class="nav-link" data-scroll-target="#worked-rejections-when-a-better-ucod-beats-the-line-written"><span class="header-section-number">8</span> 7. Worked rejections: when a better UCoD beats the line written</a></li>
  <li><a href="#does-cause-a-ucod-predict-a-garbage-underlying-cause" id="toc-does-cause-a-ucod-predict-a-garbage-underlying-cause" class="nav-link" data-scroll-target="#does-cause-a-ucod-predict-a-garbage-underlying-cause"><span class="header-section-number">9</span> 8. Does <code>Cause A == UCoD</code> predict a garbage underlying cause?</a></li>
  <li><a href="#immediate-vs-underlying-cause-which-should-drive-action" id="toc-immediate-vs-underlying-cause-which-should-drive-action" class="nav-link" data-scroll-target="#immediate-vs-underlying-cause-which-should-drive-action"><span class="header-section-number">10</span> 9. Immediate vs underlying cause — which should drive action?</a></li>
  <li><a href="#worked-example-poisoning-deaths-x-codes" id="toc-worked-example-poisoning-deaths-x-codes" class="nav-link" data-scroll-target="#worked-example-poisoning-deaths-x-codes"><span class="header-section-number">11</span> 10. Worked example: poisoning deaths (X-codes)</a></li>
  <li><a href="#non-icd-and-impossible-values-in-the-ucod" id="toc-non-icd-and-impossible-values-in-the-ucod" class="nav-link" data-scroll-target="#non-icd-and-impossible-values-in-the-ucod"><span class="header-section-number">12</span> 11. Non-ICD and impossible values in the UCoD</a></li>
  <li><a href="#what-this-means-for-automated-coding-iris-doris" id="toc-what-this-means-for-automated-coding-iris-doris" class="nav-link" data-scroll-target="#what-this-means-for-automated-coding-iris-doris"><span class="header-section-number">13</span> 12. What this means for automated coding (IRIS / DoRIS)</a></li>
  <li><a href="#reproducibility" id="toc-reproducibility" class="nav-link" data-scroll-target="#reproducibility"><span class="header-section-number">14</span> Reproducibility</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Free State Cause-of-Death Coding Quality</h1>
<p class="subtitle lead">From multiple-cause certification (Cause A–D) to the WHO underlying cause of death (UCoD)</p>
  <div class="quarto-categories">
    <div class="quarto-category">data-quality</div>
    <div class="quarto-category">cause-of-death</div>
    <div class="quarto-category">multiple-causes</div>
    <div class="quarto-category">UCoD</div>
    <div class="quarto-category">WHO</div>
    <div class="quarto-category">IRIS</div>
    <div class="quarto-category">DoRIS</div>
    <div class="quarto-category">free-state</div>
  </div>
  </div>

<div>
  <div class="description">
    Data-quality assessment of the Part I cause lines and the derived underlying cause in the Isibalo/MACOD microdata, using the Free State province as a worked example, with implications for automated coding (IRIS / DoRIS).
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 16, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="why-this-matters" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Why this matters</h1>
<p>Every death certificate in the South African civil-registration system records a <strong>sequence of causes</strong> in Part I of the medical certificate (the “Cause A → B → C → D” chain), plus contributing conditions in Part II. From that free sequence a single <strong>underlying cause of death (UCoD)</strong> is derived — the condition that, per the WHO definition, <em>“initiated the train of morbid events leading directly to death”</em> (ICD-10, Volume 2). The UCoD is what almost every published mortality statistic, cause-specific rate, and excess-mortality model ultimately uses.</p>
<p>The quality of that single UCoD is therefore only as good as (a) the underlying Cause A–D certification, and (b) the rule engine that selects the UCoD from it. This page profiles both, using the <strong>Free State</strong> province (667,081 deaths, 2006–2022) from the Isibalo/MACOD microdata as a worked, reproducible example.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Free State as the worked example
</div>
</div>
<div class="callout-body-container callout-body">
<p>The Free State subset is built by <code>data/macod_isibalo/build_free_state.R</code> from the canonical MACOD dataset (<code>load_macod.R</code>). “Free State” here means <strong>place of death</strong> (StatsSA province code 4). All metrics below recompute directly from <code>free_state_mortality.feather</code>, so the page re-renders as the data is refreshed.</p>
</div>
</div>
</section>
<section id="completeness-of-the-cause-ad-lines" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> 1. Completeness of the Cause A–D lines</h1>
<p>The first quality question is simply: <strong>is each cause line populated?</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Share of records with a real ICD code on each Part I line and on the derived UCoD, by year.</caption>
<colgroup>
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Year</th>
<th style="text-align: right;">Deaths</th>
<th style="text-align: right;">Cause A (%)</th>
<th style="text-align: right;">Cause B (%)</th>
<th style="text-align: right;">Cause C (%)</th>
<th style="text-align: right;">Cause D (%)</th>
<th style="text-align: right;">UCoD (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2006</td>
<td style="text-align: right;">53544</td>
<td style="text-align: right;">100.0</td>
<td style="text-align: right;">36.1</td>
<td style="text-align: right;">10.3</td>
<td style="text-align: right;">2.4</td>
<td style="text-align: right;">97.5</td>
</tr>
<tr class="even">
<td style="text-align: right;">2007</td>
<td style="text-align: right;">52341</td>
<td style="text-align: right;">99.9</td>
<td style="text-align: right;">36.9</td>
<td style="text-align: right;">9.9</td>
<td style="text-align: right;">2.1</td>
<td style="text-align: right;">97.3</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2008</td>
<td style="text-align: right;">50531</td>
<td style="text-align: right;">100.0</td>
<td style="text-align: right;">39.1</td>
<td style="text-align: right;">11.5</td>
<td style="text-align: right;">2.5</td>
<td style="text-align: right;">97.2</td>
</tr>
<tr class="even">
<td style="text-align: right;">2009</td>
<td style="text-align: right;">48566</td>
<td style="text-align: right;">100.0</td>
<td style="text-align: right;">36.1</td>
<td style="text-align: right;">11.4</td>
<td style="text-align: right;">2.6</td>
<td style="text-align: right;">97.3</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2010</td>
<td style="text-align: right;">46485</td>
<td style="text-align: right;">100.0</td>
<td style="text-align: right;">35.5</td>
<td style="text-align: right;">10.8</td>
<td style="text-align: right;">2.5</td>
<td style="text-align: right;">96.8</td>
</tr>
<tr class="even">
<td style="text-align: right;">2011</td>
<td style="text-align: right;">41973</td>
<td style="text-align: right;">100.0</td>
<td style="text-align: right;">36.7</td>
<td style="text-align: right;">11.3</td>
<td style="text-align: right;">2.5</td>
<td style="text-align: right;">96.8</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2012</td>
<td style="text-align: right;">36219</td>
<td style="text-align: right;">100.0</td>
<td style="text-align: right;">41.2</td>
<td style="text-align: right;">14.9</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">96.8</td>
</tr>
<tr class="even">
<td style="text-align: right;">2013</td>
<td style="text-align: right;">34514</td>
<td style="text-align: right;">100.0</td>
<td style="text-align: right;">43.4</td>
<td style="text-align: right;">16.1</td>
<td style="text-align: right;">4.3</td>
<td style="text-align: right;">96.7</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2014</td>
<td style="text-align: right;">34305</td>
<td style="text-align: right;">100.0</td>
<td style="text-align: right;">44.6</td>
<td style="text-align: right;">17.2</td>
<td style="text-align: right;">4.7</td>
<td style="text-align: right;">96.6</td>
</tr>
<tr class="even">
<td style="text-align: right;">2015</td>
<td style="text-align: right;">33534</td>
<td style="text-align: right;">100.0</td>
<td style="text-align: right;">46.4</td>
<td style="text-align: right;">18.9</td>
<td style="text-align: right;">5.5</td>
<td style="text-align: right;">100.0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2016</td>
<td style="text-align: right;">33309</td>
<td style="text-align: right;">100.0</td>
<td style="text-align: right;">46.5</td>
<td style="text-align: right;">17.9</td>
<td style="text-align: right;">4.8</td>
<td style="text-align: right;">100.0</td>
</tr>
<tr class="even">
<td style="text-align: right;">2017</td>
<td style="text-align: right;">32879</td>
<td style="text-align: right;">100.0</td>
<td style="text-align: right;">47.4</td>
<td style="text-align: right;">19.8</td>
<td style="text-align: right;">5.7</td>
<td style="text-align: right;">100.0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2018</td>
<td style="text-align: right;">30938</td>
<td style="text-align: right;">100.0</td>
<td style="text-align: right;">48.8</td>
<td style="text-align: right;">21.6</td>
<td style="text-align: right;">6.5</td>
<td style="text-align: right;">100.0</td>
</tr>
<tr class="even">
<td style="text-align: right;">2019</td>
<td style="text-align: right;">32408</td>
<td style="text-align: right;">100.0</td>
<td style="text-align: right;">47.9</td>
<td style="text-align: right;">20.1</td>
<td style="text-align: right;">5.9</td>
<td style="text-align: right;">100.0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2020</td>
<td style="text-align: right;">32929</td>
<td style="text-align: right;">100.0</td>
<td style="text-align: right;">47.7</td>
<td style="text-align: right;">20.1</td>
<td style="text-align: right;">1.4</td>
<td style="text-align: right;">100.0</td>
</tr>
<tr class="even">
<td style="text-align: right;">2021</td>
<td style="text-align: right;">40803</td>
<td style="text-align: right;">100.0</td>
<td style="text-align: right;">50.2</td>
<td style="text-align: right;">21.9</td>
<td style="text-align: right;">7.2</td>
<td style="text-align: right;">100.0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2022</td>
<td style="text-align: right;">31803</td>
<td style="text-align: right;">100.0</td>
<td style="text-align: right;">45.1</td>
<td style="text-align: right;">20.1</td>
<td style="text-align: right;">6.1</td>
<td style="text-align: right;">100.0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Reading this table.</strong> Cause A and the UCoD are essentially always present — that is expected, because a certificate with no immediate cause cannot be processed. The steep fall-off from Cause A → B → C → D is <strong>not</strong> missingness in the error sense: it reflects how many steps of the causal chain the certifier actually wrote. A certificate that legitimately has a single cause will show Cause A only. The diagnostic concern is the opposite extreme — an implausibly <strong>high</strong> share of single-line certificates (see §2).</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>The <code>888</code> / <code>000</code> placeholder trap
</div>
</div>
<div class="callout-body-container callout-body">
<p>In the raw StatsSA files, empty cause lines are not blank — they are filled with sentinel tokens such as <strong><code>888</code></strong> (“no further cause”) and <strong><code>000</code></strong>. A naïve <code>is.na()</code> or <code>nchar() &gt; 0</code> completeness check counts these as <em>populated</em>, inflating apparent multiple-cause depth to ~100%. Here they are stripped to <code>NA</code> before any counting (<code>SENTINELS</code> in the setup chunk). Any downstream analysis of Cause B–D must do the same or it will badly over-count comorbidity.</p>
</div>
</div>
</section>
<section id="multiple-cause-depth-how-rich-is-the-certification" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> 2. Multiple-cause depth (how rich is the certification?)</h1>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Distribution of the number of genuine ICD codes recorded across Cause A–D.</caption>
<thead>
<tr class="header">
<th style="text-align: right;">Real codes in Part I</th>
<th style="text-align: right;">Deaths</th>
<th style="text-align: right;">Share (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">49098</td>
<td style="text-align: right;">7.4</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">341814</td>
<td style="text-align: right;">51.2</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">176405</td>
<td style="text-align: right;">26.4</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">75185</td>
<td style="text-align: right;">11.3</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">24579</td>
<td style="text-align: right;">3.7</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/depth-trend-1.png" class="img-fluid figure-img" width="768"></p>
<figcaption>Mean number of certified causes per certificate, Free State. A rising line indicates richer (more informative) certification over time.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation.</strong> Around <strong>58.6%</strong> of Free State certificates carry at most one genuine cause code, and <strong>7.4%</strong> carry none that pass the ICD-format check (these are dominated by ill-defined <code>R</code> codes — see §5). Mean depth rises gradually across the series, which is the <em>desired</em> direction: more complete causal chains give the UCoD-selection rules more to work with. A flat or falling line, or a province stuck near “1 cause”, is a red flag for <strong>thin certification</strong> — the certifier writing only the mode of death.</p>
</section>
<section id="cause-a-vs-the-underlying-cause-the-structural-break" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> 3. Cause A vs the underlying cause — the structural break</h1>
<p>If Cause A (the immediate cause) frequently <em>equals</em> the UCoD, the certificate is effectively single-step: no causal reasoning has been encoded. Tracking <code>Cause A == UCoD</code> over time is one of the most revealing QC signals in this dataset.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/a-eq-ucod-1.png" class="img-fluid figure-img" width="768"></p>
<figcaption>Percentage of certificates where Cause A is identical to the selected underlying cause. The abrupt 2009→2010 drop marks a change in coding process, not in mortality.</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>A discontinuity that is an artefact, not an epidemiological signal
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>Cause A == UCoD</code> sits around <strong>70–73%</strong> for 2006–2009 and then <strong>collapses to ~25–30%</strong> from 2010 onward. Mortality patterns do not change that abruptly. This is the fingerprint of a <strong>change in the coding/processing pipeline</strong> (most plausibly the move toward rule-based selection of the underlying cause rather than defaulting to the first-written line). Any trend analysis that crosses 2009/2010 — including cause-specific Free State trends — must treat this as a <strong>break point</strong> and not interpret pre/post differences as real change. This is exactly the kind of issue automated coding (IRIS/DoRIS) is meant to make explicit and consistent (see §12).</p>
</div>
</div>
</section>
<section id="which-line-of-the-chain-does-the-ucod-come-from" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> 4. Which line of the chain does the UCoD come from?</h1>
<p>§3 reduced the comparison to a single yes/no: <em>does the UCoD equal Cause A?</em> But the underlying cause can legitimately be drawn from <strong>any</strong> line of the Part I chain. Under the WHO <strong>General Principle</strong>, the UCoD is the condition entered <em>alone</em> on the <strong>lowest used line</strong> of Part I, provided everything above it could plausibly have resulted from it. So the sharper, more general question — and the one most of this report turns on — is not “is the UCoD Cause A?” but <strong>“which of Cause A / B / C / D is the UCoD actually drawn from?”</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Which Part I line the underlying cause is identical to (exact code match, first match counted A→D), among the 600,360 deaths with a codeable ICD-10 UCoD.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">UCoD is identical to</th>
<th style="text-align: right;">Deaths</th>
<th style="text-align: right;">Share (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cause A (immediate)</td>
<td style="text-align: right;">245444</td>
<td style="text-align: right;">40.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cause B</td>
<td style="text-align: right;">59414</td>
<td style="text-align: right;">9.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cause C</td>
<td style="text-align: right;">12978</td>
<td style="text-align: right;">2.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cause D</td>
<td style="text-align: right;">2220</td>
<td style="text-align: right;">0.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Matches no Part I line</td>
<td style="text-align: right;">280304</td>
<td style="text-align: right;">46.7</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/chain-origin-fig-1.png" class="img-fluid figure-img" width="768"></p>
<figcaption>Origin of the underlying cause within the Part I chain, Free State (deaths with a codeable UCoD). ‘Matches no Part I line’ is dominated by code-granularity drift, not lost provenance — see the callout below.</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Most “orphan” UCoDs are granularity drift, not a broken chain
</div>
</div>
<div class="callout-body-container callout-body">
<p>Taken literally, the UCoD is <em>exactly</em> identical to one of Cause A–D in only <strong>53.3%</strong> of codeable records — and matches <strong>no</strong> Part I line in the rest, which looks alarming. But matching at the <strong>3-character ICD block</strong> level — treating <code>J18</code> on the cause line and <code>J189</code> as the UCoD as the <em>same</em> condition — lifts traceability to <strong>95.1%</strong>. That <strong>41.8-percentage-point</strong> gap is <strong>pure code-granularity drift</strong> between the certified cause lines and the derived UCoD, not a severed chain. Only <strong>4.9%</strong> of UCoDs trace to no Part I line even at block level, and almost none of those are recoverable from Part II or the injury fields. <strong>Implication:</strong> any UCoD-vs-chain reconciliation — and any IRIS/DoRIS input (§12) — must first normalise code granularity, or it will spuriously flag roughly half the records as “UCoD not in the chain”.</p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/chain-year-fig-1.png" class="img-fluid figure-img" width="768"></p>
<figcaption>Among certificates with two or more completed Part I lines, the share where the UCoD is drawn from a deeper line (Cause B/C/D) rather than the immediate Cause A. The 2009→2010 collapse is the same pipeline change seen in §3.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation.</strong> When the certificate carries a real chain (<strong>271,239</strong> certificates with ≥2 completed Part I lines), the UCoD is drawn from a <em>deeper</em> line — Cause B, C or D rather than the immediate Cause A — in <strong>27.5%</strong> of cases. That is the WHO General Principle visibly at work: the engine reaches past the immediate cause to the originating condition. But <em>how far</em> it reaches carries the now-familiar 2009/2010 fingerprint: deeper-line selection runs ~66% in 2006–2009, then drops to ~13–17% from 2010 onward. The <strong>rule that maps the Part I chain onto a single UCoD changed at that boundary</strong> — which is precisely why a legacy series and an IRIS-recoded series are not comparable across it (§12).</p>
</section>
<section id="ill-defined-and-garbage-underlying-causes-who-lens" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> 5. Ill-defined and “garbage” underlying causes (WHO lens)</h1>
<p>The WHO and the Global Burden of Disease programme classify certain UCoD values as <strong>“garbage codes”</strong> — codes that are either ill-defined (the <code>R00–R99</code> symptoms chapter) or that name a <em>mode of death</em> (e.g.&nbsp;cardiac arrest <code>I46</code>, heart failure <code>I50</code>, respiratory failure <code>J96</code>, sepsis <code>A41</code>) which cannot logically be an <em>underlying</em> cause. A high garbage-code share erodes the usefulness of cause-specific statistics.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Ill-defined and garbage-code share of the underlying cause, by year (WHO/GBD-style flag).</caption>
<thead>
<tr class="header">
<th style="text-align: right;">Year</th>
<th style="text-align: right;">Deaths</th>
<th style="text-align: right;">R99 as UCoD (%)</th>
<th style="text-align: right;">Any R-code (%)</th>
<th style="text-align: right;">Garbage UCoD (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2006</td>
<td style="text-align: right;">53544</td>
<td style="text-align: right;">10.7</td>
<td style="text-align: right;">11.1</td>
<td style="text-align: right;">20.5</td>
</tr>
<tr class="even">
<td style="text-align: right;">2007</td>
<td style="text-align: right;">52341</td>
<td style="text-align: right;">10.6</td>
<td style="text-align: right;">11.0</td>
<td style="text-align: right;">21.0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2008</td>
<td style="text-align: right;">50531</td>
<td style="text-align: right;">10.4</td>
<td style="text-align: right;">10.7</td>
<td style="text-align: right;">20.2</td>
</tr>
<tr class="even">
<td style="text-align: right;">2009</td>
<td style="text-align: right;">48566</td>
<td style="text-align: right;">12.3</td>
<td style="text-align: right;">12.8</td>
<td style="text-align: right;">23.1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2010</td>
<td style="text-align: right;">46485</td>
<td style="text-align: right;">11.4</td>
<td style="text-align: right;">12.0</td>
<td style="text-align: right;">22.8</td>
</tr>
<tr class="even">
<td style="text-align: right;">2011</td>
<td style="text-align: right;">41973</td>
<td style="text-align: right;">12.6</td>
<td style="text-align: right;">13.1</td>
<td style="text-align: right;">24.5</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2012</td>
<td style="text-align: right;">36219</td>
<td style="text-align: right;">10.8</td>
<td style="text-align: right;">11.1</td>
<td style="text-align: right;">22.5</td>
</tr>
<tr class="even">
<td style="text-align: right;">2013</td>
<td style="text-align: right;">34514</td>
<td style="text-align: right;">10.5</td>
<td style="text-align: right;">10.8</td>
<td style="text-align: right;">22.3</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2014</td>
<td style="text-align: right;">34305</td>
<td style="text-align: right;">9.7</td>
<td style="text-align: right;">10.2</td>
<td style="text-align: right;">21.7</td>
</tr>
<tr class="even">
<td style="text-align: right;">2015</td>
<td style="text-align: right;">33534</td>
<td style="text-align: right;">9.7</td>
<td style="text-align: right;">10.1</td>
<td style="text-align: right;">17.8</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2016</td>
<td style="text-align: right;">33309</td>
<td style="text-align: right;">11.0</td>
<td style="text-align: right;">11.4</td>
<td style="text-align: right;">19.1</td>
</tr>
<tr class="even">
<td style="text-align: right;">2017</td>
<td style="text-align: right;">32879</td>
<td style="text-align: right;">10.6</td>
<td style="text-align: right;">11.4</td>
<td style="text-align: right;">19.0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2018</td>
<td style="text-align: right;">30938</td>
<td style="text-align: right;">11.2</td>
<td style="text-align: right;">12.0</td>
<td style="text-align: right;">19.4</td>
</tr>
<tr class="even">
<td style="text-align: right;">2019</td>
<td style="text-align: right;">32408</td>
<td style="text-align: right;">12.3</td>
<td style="text-align: right;">12.7</td>
<td style="text-align: right;">19.6</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2020</td>
<td style="text-align: right;">32929</td>
<td style="text-align: right;">11.6</td>
<td style="text-align: right;">12.1</td>
<td style="text-align: right;">26.0</td>
</tr>
<tr class="even">
<td style="text-align: right;">2021</td>
<td style="text-align: right;">40803</td>
<td style="text-align: right;">14.3</td>
<td style="text-align: right;">14.8</td>
<td style="text-align: right;">34.8</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2022</td>
<td style="text-align: right;">31803</td>
<td style="text-align: right;">12.2</td>
<td style="text-align: right;">12.9</td>
<td style="text-align: right;">23.3</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/garbage-fig-1.png" class="img-fluid figure-img" width="768"></p>
<figcaption>Garbage-code share of the UCoD over time, Free State. The 2020–2021 spike coincides with COVID-19 pandemic disruption of certification.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation.</strong> Roughly <strong>one in five</strong> Free State deaths has an ill-defined or non-specific underlying cause in a typical year, dominated by <code>R99</code> (“ill-defined and unknown causes”). The share jumps sharply in <strong>2020–2021</strong> (peaking around 35% in 2021), consistent with pandemic-era pressure on certification and with provisional/U-coded COVID entries. For any cause-specific Free State analysis, these records either need <strong>redistribution</strong> (GBD-style) or explicit sensitivity analysis.</p>
</section>
<section id="three-ways-to-pick-the-tabulation-cause-which-is-cleanest" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> 6. Three ways to pick the tabulation cause — which is cleanest?</h1>
<p>The garbage burden in §5 was measured on the <em>processed</em> underlying cause. But that is only <strong>one of three candidate rules</strong> an analyst could use to choose the single cause a death is tabulated under. Each can be scored for ill-defined / garbage burden, and they do not agree:</p>
<ol type="1">
<li><strong>Immediate cause</strong> — just take <strong>Cause A</strong>, the first line written. Simplest, but it is the <em>mode of death</em> end of the chain.</li>
<li><strong>Lowest completed Part I line</strong> — take the deepest line the certifier filled in (Cause D if present, else C, else B, else A), as a crude proxy for “most upstream”. No selection rules applied.</li>
<li><strong>Processed UCoD (IRIS / DoRIS)</strong> — apply the WHO ICD selection and modification rules to the whole certificate. This is what the published <code>underlying_cause</code> represents, and what an IRIS/DoRIS pipeline (ICD-10 or ICD-11) would standardise.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Ill-defined / garbage burden of three candidate rules for choosing the single tabulation cause, Free State (all years).</caption>
<colgroup>
<col style="width: 38%">
<col style="width: 27%">
<col style="width: 11%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Selection rule</th>
<th style="text-align: right;">Garbage / ill-defined (%)</th>
<th style="text-align: right;">R-code (%)</th>
<th style="text-align: right;">Missing / non-ICD (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1. Immediate cause (Cause A)</td>
<td style="text-align: right;">29.6</td>
<td style="text-align: right;">12.1</td>
<td style="text-align: right;">7.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">2. Lowest completed Part I line</td>
<td style="text-align: right;">29.5</td>
<td style="text-align: right;">11.9</td>
<td style="text-align: right;">7.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3. Processed UCoD (IRIS/DoRIS-style)</td>
<td style="text-align: right;">22.3</td>
<td style="text-align: right;">11.8</td>
<td style="text-align: right;">10.0</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/three-methods-fig-1.png" class="img-fluid figure-img" width="768"></p>
<figcaption>Garbage / ill-defined share by year under each of the three selection rules, Free State. The processed UCoD is consistently the cleanest; taking the lowest completed line is no better — often worse — than the immediate cause.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation.</strong> The three rules are <em>not</em> interchangeable. Taking the <strong>immediate cause</strong> leaves <strong>29.6%</strong> garbage and taking the <strong>lowest completed line</strong> leaves <strong>29.5%</strong> — essentially the same, and in several years the lowest line is actually <em>worse</em>. That is counter-intuitive until you remember the chain is often written <strong>out of order or padded</strong>: the last filled line is frequently itself a mode of death (<code>R99</code>, cardiac/respiratory arrest), so “go deepest” does not mean “go most upstream”. Only the <strong>rule-based processed UCoD</strong> meaningfully reduces the burden, to <strong>22.3%</strong>, because the WHO selection/modification rules can <em>reject</em> an ill-defined line in favour of a specific one elsewhere on the certificate.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>What this says about IRIS / DoRIS and ICD-10 vs ICD-11
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Automated processing earns its keep here.</strong> The ~7-point gap between the immediate cause and the processed UCoD is the value the WHO selection rules add — and it is exactly that logic IRIS/DoRIS encode <em>reproducibly</em>. A naive “Cause A” or “lowest line” tabulation throws that away.</li>
<li><strong>It is a floor, not a fix.</strong> Even the processed UCoD sits at 22.3% garbage. IRIS/DoRIS standardise <em>selection</em>; they do not invent specificity where the certificate only ever named a symptom. Garbage-code redistribution (§5) is still required afterwards.</li>
<li><strong>ICD-10 → ICD-11.</strong> Re-coding under ICD-11 (with its different chapter structure, post-coordination, and revised modes-of-death handling) is itself a <em>fourth</em> rule and will shift these numbers again. As with the 2009/2010 break (§3–§4), an ICD-10 series and an ICD-11 series are <strong>not directly comparable</strong>; any migration needs a dual-coded bridge period on a subset like this one.</li>
</ul>
</div>
</div>
</section>
<section id="worked-rejections-when-a-better-ucod-beats-the-line-written" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> 7. Worked rejections: when a better UCoD beats the line written</h1>
<p>§6 argued in aggregate that the processed UCoD carries less garbage than the immediate cause or the lowest line. This section makes that <strong>concrete</strong> by pulling real Free State certificates where the immediate cause (Cause A) is a <em>mode of death</em> — cardiac arrest, respiratory failure, sepsis, dehydration — and the WHO rules correctly <strong>reject it</strong> and select a specific underlying cause from elsewhere on the certificate. These are exactly the cases an IRIS/DoRIS pipeline handles automatically and a naive “Cause A” or “lowest line” tabulation gets wrong.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>The 12 most common rejections in the Free State data: Cause A is a non-specific mode of death, but the rules select a specific underlying cause from another line. These 68,994 certificates (10.3% of all deaths) would be mis-tabulated by an immediate-cause rule.</caption>
<colgroup>
<col style="width: 47%">
<col style="width: 40%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Immediate cause written (Cause A) — a mode of death</th>
<th style="text-align: left;">Underlying cause selected instead (UCoD)</th>
<th style="text-align: left;">Certificates</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">E86 Volume depletion (dehydration)</td>
<td style="text-align: left;">A09 Infectious gastroenteritis / diarrhoea</td>
<td style="text-align: left;">4,651</td>
</tr>
<tr class="even">
<td style="text-align: left;">I50 Heart failure</td>
<td style="text-align: left;">I11 Hypertensive heart disease</td>
<td style="text-align: left;">2,217</td>
</tr>
<tr class="odd">
<td style="text-align: left;">J96 Respiratory failure</td>
<td style="text-align: left;">J18 Pneumonia, organism unspecified</td>
<td style="text-align: left;">1,775</td>
</tr>
<tr class="even">
<td style="text-align: left;">J96 Respiratory failure</td>
<td style="text-align: left;">A16 Respiratory tuberculosis</td>
<td style="text-align: left;">1,732</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I46 Cardiac arrest</td>
<td style="text-align: left;">I10 Essential hypertension</td>
<td style="text-align: left;">1,382</td>
</tr>
<tr class="even">
<td style="text-align: left;">I50 Heart failure</td>
<td style="text-align: left;">E14 Diabetes mellitus (unspecified)</td>
<td style="text-align: left;">1,148</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I46 Cardiac arrest</td>
<td style="text-align: left;">E14 Diabetes mellitus (unspecified)</td>
<td style="text-align: left;">1,084</td>
</tr>
<tr class="even">
<td style="text-align: left;">A41 Sepsis</td>
<td style="text-align: left;">E14 Diabetes mellitus (unspecified)</td>
<td style="text-align: left;">1,022</td>
</tr>
<tr class="odd">
<td style="text-align: left;">J96 Respiratory failure</td>
<td style="text-align: left;">J44 COPD</td>
<td style="text-align: left;">731</td>
</tr>
<tr class="even">
<td style="text-align: left;">N19 Unspecified kidney failure</td>
<td style="text-align: left;">E14 Diabetes mellitus (unspecified)</td>
<td style="text-align: left;">718</td>
</tr>
<tr class="odd">
<td style="text-align: left;">E86 Volume depletion (dehydration)</td>
<td style="text-align: left;">D84 Immunodeficiency (HIV-associated)</td>
<td style="text-align: left;">671</td>
</tr>
<tr class="even">
<td style="text-align: left;">J96 Respiratory failure</td>
<td style="text-align: left;">B20 HIV disease</td>
<td style="text-align: left;">658</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>How to read these pairs.</strong> Every row is a place where “tabulate the immediate cause” would have recorded a <em>non-actionable mode of death</em> and the WHO selection rules recovered the real story:</p>
<ul>
<li><strong>Dehydration → diarrhoeal disease</strong> (<code>E86 → A09</code>, the single most common rejection): the patient died dehydrated, but the <em>cause</em> was infectious gastroenteritis. An immediate-cause count would log “volume depletion”; the UCoD correctly logs a vaccine-/WASH-preventable enteric infection.</li>
<li><strong>Cardiac arrest → hypertension</strong> (<code>I46 → I10</code>) and <strong>heart failure → hypertensive heart disease</strong> (<code>I50 → I11</code>): the heart stopping is the mode; hypertension is the modifiable underlying cause a programme would target.</li>
<li><strong>Respiratory failure → pneumonia or TB</strong> (<code>J96 → J18</code> / <code>A16</code>): “the lungs failed” versus a treatable infection — and in South Africa often <strong>TB</strong>, which has completely different surveillance implications.</li>
<li><strong>Sepsis → diabetes, pneumonia, or HIV-related immunodeficiency</strong> (<code>A41 → E14</code> / <code>J18</code> / <code>D84</code>): sepsis is the final common pathway; the UCoD names the chronic condition that let it happen.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>For each canonical mode of death appearing as the immediate cause, how often it is rejected and the specific underlying causes chosen in its place, Free State.</caption>
<colgroup>
<col style="width: 19%">
<col style="width: 11%">
<col style="width: 69%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Mode of death on Cause A</th>
<th style="text-align: left;">Certificates rejected</th>
<th style="text-align: left;">Top underlying causes selected instead</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">E86 Volume depletion (dehydration)</td>
<td style="text-align: left;">9,041</td>
<td style="text-align: left;">A09 Infectious gastroenteritis / diarrhoea (4651); D84 Immunodeficiency (HIV-associated) (671); B33 Viral disease (343)</td>
</tr>
<tr class="even">
<td style="text-align: left;">I46 Cardiac arrest</td>
<td style="text-align: left;">10,756</td>
<td style="text-align: left;">I10 Essential hypertension (1382); E14 Diabetes mellitus (unspecified) (1084); I64 Stroke, unspecified (531)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I50 Heart failure</td>
<td style="text-align: left;">11,497</td>
<td style="text-align: left;">I11 Hypertensive heart disease (2217); E14 Diabetes mellitus (unspecified) (1148); J18 Pneumonia, organism unspecified (647)</td>
</tr>
<tr class="even">
<td style="text-align: left;">J96 Respiratory failure</td>
<td style="text-align: left;">12,555</td>
<td style="text-align: left;">J18 Pneumonia, organism unspecified (1775); A16 Respiratory tuberculosis (1732); J44 COPD (731)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A41 Sepsis</td>
<td style="text-align: left;">9,470</td>
<td style="text-align: left;">E14 Diabetes mellitus (unspecified) (1022); J18 Pneumonia, organism unspecified (593); D84 Immunodeficiency (HIV-associated) (463)</td>
</tr>
<tr class="even">
<td style="text-align: left;">N19 Unspecified kidney failure</td>
<td style="text-align: left;">5,209</td>
<td style="text-align: left;">E14 Diabetes mellitus (unspecified) (718); B33 Viral disease (459); B23 HIV disease (376)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">N18 Chronic kidney disease</td>
<td style="text-align: left;">1,807</td>
<td style="text-align: left;">E14 Diabetes mellitus (unspecified) (340); I12 — (248); B23 HIV disease (188)</td>
</tr>
<tr class="even">
<td style="text-align: left;">R57 —</td>
<td style="text-align: left;">469</td>
<td style="text-align: left;">A09 Infectious gastroenteritis / diarrhoea (117); K92 — (23); I21 Acute myocardial infarction (19)</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Twelve real Free State certificate chains where the rules looked past a mode-of-death immediate cause to a specific underlying cause deeper in Part I.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Part I chain as written (A → B → C → D)</th>
<th style="text-align: left;">UCoD selected</th>
<th style="text-align: left;">Certificates</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">E86 → A09 → · → ·</td>
<td style="text-align: left;">A09</td>
<td style="text-align: left;">2,702</td>
</tr>
<tr class="even">
<td style="text-align: left;">J969 → J189 → · → ·</td>
<td style="text-align: left;">J18</td>
<td style="text-align: left;">985</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I469 → I10 → · → ·</td>
<td style="text-align: left;">I10</td>
<td style="text-align: left;">980</td>
</tr>
<tr class="even">
<td style="text-align: left;">I500 → I10 → · → ·</td>
<td style="text-align: left;">I11</td>
<td style="text-align: left;">962</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I509 → I10 → · → ·</td>
<td style="text-align: left;">I11</td>
<td style="text-align: left;">778</td>
</tr>
<tr class="even">
<td style="text-align: left;">E86 → A099 → · → ·</td>
<td style="text-align: left;">A09</td>
<td style="text-align: left;">659</td>
</tr>
<tr class="odd">
<td style="text-align: left;">J96 → J18 → · → ·</td>
<td style="text-align: left;">J18</td>
<td style="text-align: left;">467</td>
</tr>
<tr class="even">
<td style="text-align: left;">J969 → J22 → · → ·</td>
<td style="text-align: left;">J22</td>
<td style="text-align: left;">378</td>
</tr>
<tr class="odd">
<td style="text-align: left;">J969 → A162 → · → ·</td>
<td style="text-align: left;">A16</td>
<td style="text-align: left;">369</td>
</tr>
<tr class="even">
<td style="text-align: left;">J96 → A16 → · → ·</td>
<td style="text-align: left;">A16</td>
<td style="text-align: left;">328</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A419 → J189 → · → ·</td>
<td style="text-align: left;">J18</td>
<td style="text-align: left;">308</td>
</tr>
<tr class="even">
<td style="text-align: left;">E86 → A09 → D84 → ·</td>
<td style="text-align: left;">A09</td>
<td style="text-align: left;">255</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Why this strengthens the case for rule-based UCoD selection
</div>
</div>
<div class="callout-body-container callout-body">
<p>These are not edge cases — <strong>68,994 certificates (10.3% of all Free State deaths)</strong> have a mode of death on the immediate line that the rules correctly override. The lowest-line rule does little better: it still leaves <strong>16,555</strong> certificates with a garbage deepest line that the processed UCoD improves on, because certifiers often write the mode of death <em>last</em>. The reproducible application of the WHO selection and modification rules — which is precisely what <strong>IRIS / DoRIS</strong> automate — is what converts “the heart stopped / the lungs failed / the patient was septic” into hypertension, pneumonia, TB, diabetes, and HIV: the causes that actually drive prevention policy. This is the mechanism behind the aggregate gap in §6.</p>
</div>
</div>
</section>
<section id="does-cause-a-ucod-predict-a-garbage-underlying-cause" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> 8. Does <code>Cause A == UCoD</code> predict a garbage underlying cause?</h1>
<p>§3 showed that a large share of certificates are <em>single-step</em> — Cause A is carried straight through as the UCoD, with no causal chain encoded. A natural quality question is whether those single-step certificates are also the ones most likely to produce an <strong>ill-defined / garbage UCoD</strong>. If so, <code>Cause A == UCoD</code> is not merely a marker of a thin chain; it is a leading indicator of low-specificity output.</p>
<p>To avoid a spurious result, this section is restricted to records with a <strong>codeable (real ICD-10) UCoD</strong>. A missing/sentinel UCoD can never equal Cause A by construction, so including those records would manufacture an association.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Garbage/ill-defined share of the underlying cause, by whether the immediate cause (Cause A) was carried straight through as the UCoD. Restricted to records with a codeable ICD-10 UCoD.</caption>
<colgroup>
<col style="width: 39%">
<col style="width: 10%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Cause A == UCoD</th>
<th style="text-align: right;">Deaths</th>
<th style="text-align: right;">Garbage UCoD (n)</th>
<th style="text-align: right;">Garbage UCoD (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">No (UCoD from deeper line)</td>
<td style="text-align: right;">354869</td>
<td style="text-align: right;">46593</td>
<td style="text-align: right;">13.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yes (single-step)</td>
<td style="text-align: right;">245444</td>
<td style="text-align: right;">90296</td>
<td style="text-align: right;">36.8</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/aeq-garbage-trend-1.png" class="img-fluid figure-img" width="768"></p>
<figcaption>Garbage-UCoD share by year, split by whether the certificate was single-step (Cause A = UCoD) or had the UCoD selected from a deeper Part I line, Free State.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation.</strong> Among single-step certificates (<code>Cause A = UCoD</code>), <strong>36.8%</strong> carry a garbage/ill-defined UCoD, versus <strong>13.1%</strong> where the UCoD was selected from a deeper line — a relative risk of <strong>2.8</strong> (95% CI 2.8–2.8; χ² p &lt; 0.001). The mechanism is direct: when the certifier writes only a mode of death or an <code>R</code>-code on the first line and nothing beneath it, that single token becomes <em>both</em> Cause A and the UCoD. <code>Cause A == UCoD</code> is therefore not just a “thin chain” flag — it is a cheap, single-field <strong>data-quality KPI</strong> that can be monitored prospectively: a rising share of single-step certificates predicts a rising share of uninformative underlying causes, and the two co-spike in the 2020–2021 pandemic years.</p>
</section>
<section id="immediate-vs-underlying-cause-which-should-drive-action" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> 9. Immediate vs underlying cause — which should drive action?</h1>
<p>The WHO underlying cause is the standard tabulation cause and the correct denominator for primary-prevention targets and international comparability. But <em>“the condition that initiated the chain”</em> is not always the condition a health system could have acted on in the final illness. This section challenges the reflex of collapsing every death to a single UCoD by asking what information is <strong>discarded</strong> when we move from the immediate cause (Cause A) to the UCoD.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>ICD-chapter distribution of the immediate cause (Cause A) vs the underlying cause, among deaths where both are codeable. The shift column shows where the UCoD adds (+) or removes (−) weight relative to the immediate cause.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Chapter</th>
<th style="text-align: right;">Cause A (%)</th>
<th style="text-align: right;">UCoD (%)</th>
<th style="text-align: right;">Shift (UCoD - A)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">I Infectious &amp; parasitic</td>
<td style="text-align: right;">17.1</td>
<td style="text-align: right;">22.5</td>
<td style="text-align: right;">5.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">IX Circulatory</td>
<td style="text-align: right;">20.9</td>
<td style="text-align: right;">17.9</td>
<td style="text-align: right;">-3.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">X Respiratory</td>
<td style="text-align: right;">21.9</td>
<td style="text-align: right;">15.1</td>
<td style="text-align: right;">-6.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">XVIII Ill-defined (R)</td>
<td style="text-align: right;">13.4</td>
<td style="text-align: right;">13.1</td>
<td style="text-align: right;">-0.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IV Endocrine / metabolic</td>
<td style="text-align: right;">5.5</td>
<td style="text-align: right;">6.7</td>
<td style="text-align: right;">1.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">II Neoplasms</td>
<td style="text-align: right;">4.9</td>
<td style="text-align: right;">6.6</td>
<td style="text-align: right;">1.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">III Blood &amp; immune</td>
<td style="text-align: right;">1.8</td>
<td style="text-align: right;">4.2</td>
<td style="text-align: right;">2.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">XVI Perinatal</td>
<td style="text-align: right;">3.9</td>
<td style="text-align: right;">3.9</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">XI Digestive</td>
<td style="text-align: right;">2.9</td>
<td style="text-align: right;">2.8</td>
<td style="text-align: right;">-0.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">VI Nervous system</td>
<td style="text-align: right;">2.5</td>
<td style="text-align: right;">2.3</td>
<td style="text-align: right;">-0.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">XIV Genitourinary</td>
<td style="text-align: right;">2.7</td>
<td style="text-align: right;">1.9</td>
<td style="text-align: right;">-0.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">U Special (incl.&nbsp;COVID)</td>
<td style="text-align: right;">1.3</td>
<td style="text-align: right;">1.6</td>
<td style="text-align: right;">0.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">V Mental &amp; behavioural</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">0.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">XVII Congenital</td>
<td style="text-align: right;">0.3</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">0.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">XIII Musculoskeletal</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">0.3</td>
<td style="text-align: right;">0.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">XII Skin</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">XV Pregnancy &amp; childbirth</td>
<td style="text-align: right;">0.3</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">-0.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">VII–VIII Eye &amp; ear</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.0</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/chapter-diverge-1.png" class="img-fluid figure-img" width="768"></p>
<figcaption>Percentage-point shift in chapter weight when moving from the immediate cause to the underlying cause. Positive (blue) = the chapter is up-weighted by the UCoD (what to prevent); negative (orange) = down-weighted (proximate killers retained by the immediate cause).</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>For the six most common underlying-cause chapters, the immediate causes (Cause A) most often recorded on the same certificates — i.e.&nbsp;the proximate conditions that preceded death.</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 10%">
<col style="width: 69%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Underlying cause chapter</th>
<th style="text-align: left;">UCoD deaths</th>
<th style="text-align: left;">Most common immediate causes (Cause A chapter)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">I Infectious &amp; parasitic</td>
<td style="text-align: left;">134,690</td>
<td style="text-align: left;">I Infectious &amp; parasitic — 67%; X Respiratory — 14%; IV Endocrine / metabolic — 6%</td>
</tr>
<tr class="even">
<td style="text-align: left;">IX Circulatory</td>
<td style="text-align: left;">107,159</td>
<td style="text-align: left;">IX Circulatory — 86%; X Respiratory — 7%; XIV Genitourinary — 2%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">X Respiratory</td>
<td style="text-align: left;">90,437</td>
<td style="text-align: left;">X Respiratory — 89%; IX Circulatory — 6%; I Infectious &amp; parasitic — 1%</td>
</tr>
<tr class="even">
<td style="text-align: left;">XVIII Ill-defined (R)</td>
<td style="text-align: left;">78,527</td>
<td style="text-align: left;">XVIII Ill-defined (R) — 97%; IX Circulatory — 2%; U Special (incl.&nbsp;COVID) — 1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IV Endocrine / metabolic</td>
<td style="text-align: left;">40,057</td>
<td style="text-align: left;">IV Endocrine / metabolic — 45%; IX Circulatory — 27%; X Respiratory — 12%</td>
</tr>
<tr class="even">
<td style="text-align: left;">II Neoplasms</td>
<td style="text-align: left;">39,421</td>
<td style="text-align: left;">II Neoplasms — 72%; X Respiratory — 9%; IX Circulatory — 7%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>What the data show.</strong> In <strong>24.2%</strong> of Free State deaths the immediate cause and the UCoD fall in <strong>different ICD chapters</strong> — moving to the UCoD changes the clinical story, not just the code. The shift is systematic (chart above): the UCoD up-weights <strong>I Infectious &amp; parasitic</strong> while the immediate cause retains weight in <strong>X Respiratory</strong> and the other mode-of-death / ill-defined / respiratory chapters. The transition table makes the point concrete: chronic underlying causes are reached <em>through</em> a small set of treatable proximate conditions (infections, respiratory failure, ill-defined collapse).</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>The case for not collapsing everything to the UCoD
</div>
</div>
<div class="callout-body-container callout-body">
<p>The UCoD and the immediate cause answer <strong>different action questions</strong>:</p>
<ul>
<li><strong>UCoD → “what should we prevent?”</strong> It points upstream to the modifiable risk (hypertension, HIV, diabetes, tobacco) and is the right basis for primary-prevention policy and inter-country comparison.</li>
<li><strong>Immediate cause → “what could the health system have intervened on?”</strong> It names the proximate, often <em>treatable</em> event in the final illness (the sepsis, the bleed, the respiratory failure) — the signal a hospital or district quality-of-care review actually needs.</li>
</ul>
<p>Using the UCoD as the <em>sole</em> information for action silently discards the second question for 24.2% of deaths. The defensible position is <strong>multiple-cause analysis (MCOD)</strong> — report the UCoD for prevention targets <em>and</em> the immediate/contributing causes for service-delivery action — rather than swapping one for the other.</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Caveat: the immediate cause is itself noisier
</div>
</div>
<div class="callout-body-container callout-body">
<p>This is an argument for using <em>both</em>, not for replacing the UCoD. The immediate cause carries a <strong>higher</strong> share of <code>R</code>-codes and modes of death (§5–6), so a naïve “Cause A only” tabulation would be even less specific than the UCoD. The actionable middle ground is structured MCOD reporting, ideally after the sentinel-cleaning and automated-selection steps described in §12.</p>
</div>
</div>
</section>
<section id="worked-example-poisoning-deaths-x-codes" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> 10. Worked example: poisoning deaths (X-codes)</h1>
<p>Poisoning is an ideal stress-test of the immediate-vs-underlying question because it is an <strong>external cause</strong>. Under WHO rules a poisoning certificate should carry <em>two complementary codes</em>: the <strong>external cause</strong> (the <em>how</em> and <em>intent</em> — an <code>X</code> code: accidental, self-inflicted, or assault) and the <strong>nature of injury</strong> (the <em>what</em> — a <code>T36–T65</code> toxic-effect code naming the substance’s clinical effect). The external cause is the WHO underlying cause; the nature-of-injury and any organ failure are the proximate, clinically actionable events. Poisoning therefore lets us see, in one well-defined group, exactly what the move to a single UCoD keeps and what it discards.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>First: does the Isibalo/MACOD extract retain unnatural deaths?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Yes. In the Free State subset, <code>natural_unnatural == 2</code> (unnatural) covers <strong>54,956</strong> deaths and a further <strong>13,302</strong> are coded <code>8</code> (manner undetermined); external-cause <code>V/W/X/Y</code> codes appear as the UCoD in <strong>54,957</strong> records — effectively all the unnatural deaths. Injury deaths are <em>not</em> dropped from the extract, so a poisoning analysis is possible. (<code>build_free_state.R</code> carries <code>natural_unnatural</code> and the full <code>injury_a–d</code> / <code>underlying_injury</code> fields through from <code>load_macod.R</code>.)</p>
</div>
</div>
<p>Poisoning here is defined <strong>tightly</strong> by the external-cause X-code, excluding the garbage <code>X59</code> (“exposure to unspecified factor”) and <code>X09</code> which are the external-cause analogue of <code>R99</code>:</p>
<ul>
<li><strong>Accidental</strong> poisoning: <code>X40–X49</code></li>
<li><strong>Intentional self-poisoning</strong> (suicide): <code>X60–X69</code></li>
<li><strong>Assault</strong> by poisoning: <code>X85–X90</code></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Free State poisoning deaths (n = 1,094) by intent, classified from the underlying external-cause X-code.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Intent (external cause)</th>
<th style="text-align: right;">Deaths</th>
<th style="text-align: right;">Share (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Accidental (X40–49)</td>
<td style="text-align: right;">918</td>
<td style="text-align: right;">83.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Assault (X85–90)</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Intentional self-poisoning (X60–69)</td>
<td style="text-align: right;">175</td>
<td style="text-align: right;">16.0</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>How the poisoning certificate is structured: the external cause is duplicated as the immediate cause, and the clinical nature-of-injury code is almost never present.</caption>
<colgroup>
<col style="width: 69%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Metric</th>
<th style="text-align: right;">Share of poisoning deaths (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Immediate cause (Cause A) is itself the X-code</td>
<td style="text-align: right;">55.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cause A is identical to the underlying external cause (single-step)</td>
<td style="text-align: right;">51.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Any nature-of-injury toxic-effect code (T36–T65) recorded</td>
<td style="text-align: right;">20.2</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Most common underlying poisoning codes, Free State. X48/X68 = pesticides; X49/X40/X44 = unspecified or other chemicals/drugs; X60–X69 = intentional self-poisoning.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Underlying external cause</th>
<th style="text-align: right;">Deaths</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">X49</td>
<td style="text-align: right;">507</td>
</tr>
<tr class="even">
<td style="text-align: left;">X48</td>
<td style="text-align: right;">226</td>
</tr>
<tr class="odd">
<td style="text-align: left;">X64</td>
<td style="text-align: right;">102</td>
</tr>
<tr class="even">
<td style="text-align: left;">X44</td>
<td style="text-align: right;">85</td>
</tr>
<tr class="odd">
<td style="text-align: left;">X47</td>
<td style="text-align: right;">55</td>
</tr>
<tr class="even">
<td style="text-align: left;">X68</td>
<td style="text-align: right;">29</td>
</tr>
<tr class="odd">
<td style="text-align: left;">X69</td>
<td style="text-align: right;">22</td>
</tr>
<tr class="even">
<td style="text-align: left;">X46</td>
<td style="text-align: right;">16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">X45</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="even">
<td style="text-align: left;">X67</td>
<td style="text-align: right;">9</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/poison-year-1.png" class="img-fluid figure-img" width="768"></p>
<figcaption>Free State poisoning deaths by year and intent. The 2021–2022 rise most plausibly reflects improved external-cause capture in the 2022 data vintage rather than a true epidemic — a comparability caveat, not a finding.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>What the poisoning case shows.</strong> For these 1,094 deaths the immediate cause and the underlying cause are essentially the <strong>same single X-code</strong>: Cause A is identical to the underlying external cause in <strong>51.4%</strong> of records, and a nature-of-injury toxic-effect code (<code>T36–T65</code>) — the part that names <em>what the poison did to the body</em> — is recorded in only <strong>20.2%</strong>. In other words, the certificate captures the <em>how/why</em> (intent + agent, which is exactly what the UCoD needs) but discards the <em>clinical what</em> (the toxidrome / organ failure that a clinician or a poisons-centre audit would act on).</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Immediate vs underlying — the action split, made concrete
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Underlying cause (the X-code) → prevention.</strong> It tells us 175 deaths were <strong>intentional self-poisoning</strong> (a mental-health and means-restriction signal) and that pesticides (<code>X48</code>/<code>X68</code>, 255 deaths) are a leading agent in this largely agricultural province (a regulatory / agrochemical-access signal). This is genuinely actionable upstream information that the UCoD captures well.</li>
<li><strong>Immediate / nature-of-injury → clinical care.</strong> The toxic effect and the proximate organ failure — what the emergency unit actually managed — are mostly <strong>absent</strong>. So for poisoning, the <em>clinical</em> action question is the one the data cannot currently answer, regardless of which single cause we tabulate.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Two data-quality flags specific to poisoning
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><strong>Agent specificity is poor.</strong> A large share of accidental poisonings are coded to non-specific chemicals (<code>X49</code>/<code>X40</code>/<code>X44</code>, 54.8% of poisoning deaths) — the external-cause analogue of the <code>R99</code> problem in §5. This blunts both prevention targeting and intent classification.</li>
<li><strong>The 2021–2022 surge is a comparability artefact, not an epidemic.</strong> The jump in counts coincides with the 2022 data vintage’s richer external-cause coding (the same vintage change discussed for causes in §3). Treat cross-vintage poisoning trends with caution and anchor any time series to a consistent coding era.</li>
</ol>
</div>
</div>
<p>The practical message mirrors §9: the UCoD is the right tabulation cause for <strong>poisoning prevention</strong> (intent + agent), but a poisoning audit aimed at <strong>clinical care</strong> needs the nature-of-injury and contributing conditions, which are systematically thin here. Automated coding (§12) can enforce the external-cause + nature-of-injury <em>pairing</em> WHO expects, but it cannot create a <code>T</code>-code the certifier never wrote.</p>
</section>
<section id="non-icd-and-impossible-values-in-the-ucod" class="level1" data-number="12">
<h1 data-number="12"><span class="header-section-number">12</span> 11. Non-ICD and impossible values in the UCoD</h1>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Most common underlying-cause values that are NOT well-formed ICD-10 codes (sentinels + external-cause codes used directly).</caption>
<thead>
<tr class="header">
<th style="text-align: left;">UCoD value</th>
<th style="text-align: right;">Deaths</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">X59</td>
<td style="text-align: right;">15966</td>
</tr>
<tr class="even">
<td style="text-align: left;">(missing/sentinel)</td>
<td style="text-align: right;">11764</td>
</tr>
<tr class="odd">
<td style="text-align: left;">X99</td>
<td style="text-align: right;">6885</td>
</tr>
<tr class="even">
<td style="text-align: left;">V89</td>
<td style="text-align: right;">4517</td>
</tr>
<tr class="odd">
<td style="text-align: left;">W76</td>
<td style="text-align: right;">3724</td>
</tr>
<tr class="even">
<td style="text-align: left;">W34</td>
<td style="text-align: right;">3569</td>
</tr>
<tr class="odd">
<td style="text-align: left;">X09</td>
<td style="text-align: right;">2662</td>
</tr>
<tr class="even">
<td style="text-align: left;">W74</td>
<td style="text-align: right;">1974</td>
</tr>
<tr class="odd">
<td style="text-align: left;">V49</td>
<td style="text-align: right;">1937</td>
</tr>
<tr class="even">
<td style="text-align: left;">Y34</td>
<td style="text-align: right;">1904</td>
</tr>
<tr class="odd">
<td style="text-align: left;">V09</td>
<td style="text-align: right;">954</td>
</tr>
<tr class="even">
<td style="text-align: left;">Y29</td>
<td style="text-align: right;">951</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Note the presence of <strong>external-cause codes</strong> (<code>V</code>, <code>W</code>, <code>X</code>, <code>Y</code> chapters — e.g. <code>X59</code> exposure to unspecified factor, <code>X99</code> assault by sharp object, <code>V89</code> traffic) appearing as the underlying cause. These are valid ICD codes but, under WHO rules, an external cause should be paired with the <em>nature-of-injury</em> code; their appearance as a bare UCoD is a known certification/coding quality issue for injury deaths and should be cross-checked against the <code>injury_a–d</code> fields.</p>
</section>
<section id="what-this-means-for-automated-coding-iris-doris" class="level1" data-number="13">
<h1 data-number="13"><span class="header-section-number">13</span> 12. What this means for automated coding (IRIS / DoRIS)</h1>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>IRIS (the Iris Institute / DIMDI rule engine, built on the NCHS ACME/MICAR logic) and <strong>DoRIS</strong> are tools that take the Cause A–D text/codes and <strong>deterministically select the underlying cause</strong> using the WHO ICD-10 selection and modification rules. Moving Free State / national certification onto IRIS or DoRIS would standardise UCoD selection — but the issues surfaced above will translate into specific failure modes. Anticipated issues:</p>
</div>
</div>
<p><strong>A. Input-quality issues (garbage in → garbage out).</strong></p>
<ul>
<li><strong>Sentinel codes (<code>888</code>, <code>000</code>)</strong> must be mapped to “no entry” before the engine runs. If passed through, IRIS will either reject the record or treat them as real conditions, corrupting the selection.</li>
<li><strong>Thin certification</strong> (§2–3): when ~50% of certificates carry a single cause, the rule engine has no chain to reason over and will simply echo Cause A. The apparent “improvement” from automation will be small where input depth is low — the gain from IRIS is proportional to certification richness.</li>
<li><strong>Ill-defined Cause A (<code>R99</code>, modes of death)</strong> (§5): IRIS will faithfully carry an ill-defined immediate cause through to the UCoD when nothing better is present. Automation does <strong>not</strong> fix <code>R99</code>; it only makes the selection reproducible. Garbage-code redistribution is a separate, post-IRIS step.</li>
</ul>
<p><strong>B. Mapping &amp; version issues.</strong></p>
<ul>
<li><strong>ICD-10 version drift.</strong> IRIS is keyed to a specific ICD-10 update/edition. South African historical files (2006–2022) may mix code vintages and use 3-character vs 4-character codes inconsistently (e.g.&nbsp;<code>J18</code> vs <code>J189</code> both appear). Codes must be normalised to the granularity IRIS expects, or valid codes will be flagged as unknown.</li>
<li><strong>Local / non-standard codes.</strong> Sentinels and StatsSA-specific groupings (<code>underlying_broad_grp</code>, <code>underlying_main_grp</code>) are not ICD and must be excluded from the IRIS input.</li>
</ul>
<p><strong>C. Structural / comparability issues.</strong></p>
<ul>
<li><strong>The 2009/2010 break (§3)</strong> means a back-series re-coded with IRIS will <em>not</em> be comparable to the legacy UCoD series. Re-coding the whole history through one engine is the cleanest fix, but it changes published numbers — this must be communicated as a methods change, not a data revision.</li>
<li><strong>Part I vs Part II placement.</strong> IRIS treats Part I (the causal chain) and Part II (contributing conditions) differently. In this dataset the Part II fields (<code>part2_cause_a/b</code>) are only present from ~2009; feeding them in inconsistently across years will produce year-dependent UCoD behaviour.</li>
<li><strong>External causes</strong> (§11): IRIS expects the underlying (external) cause and the injury/nature code together. The split <code>cause_*</code> / <code>injury_*</code> layout here must be reassembled into the WHO certificate structure before coding, or injury deaths will be mis-selected.</li>
</ul>
<p><strong>D. Process recommendations.</strong></p>
<ol type="1">
<li><strong>Pre-clean</strong> all cause lines to NA-out sentinels (<code>888</code>, <code>000</code>, …) and normalise code granularity before any IRIS/DoRIS run.</li>
<li><strong>Re-code the full back-series</strong> through a single engine/version to remove the 2010 discontinuity, and publish legacy vs re-coded side-by-side.</li>
<li><strong>Keep a garbage-code redistribution stage</strong> <em>after</em> automated selection — IRIS standardises selection, it does not improve specificity.</li>
<li><strong>Validate on the Free State subset first</strong> (this file): compare IRIS-selected UCoD against the existing <code>underlying_cause</code>, quantify concordance, and inspect the discordant cases by ICD chapter before scaling nationally.</li>
</ol>
</section>
<section id="reproducibility" class="level1" data-number="14">
<h1 data-number="14"><span class="header-section-number">14</span> Reproducibility</h1>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 22%">
<col style="width: 77%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Item</th>
<th style="text-align: left;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Source dataset</td>
<td style="text-align: left;">free_state_mortality.feather (build_free_state.R → load_macod.R)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Geography</td>
<td style="text-align: left;">Free State, place of death (StatsSA prov = 4)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Records</td>
<td style="text-align: left;">667,081</td>
</tr>
<tr class="even">
<td style="text-align: left;">Years</td>
<td style="text-align: left;">2006–2022</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sentinels stripped</td>
<td style="text-align: left;">…., XXXX, 888, 000, 8888, 9999, 9996, 9998</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>All figures recompute from the Free State feather at render time. To refresh the data: rebuild the canonical dataset (<code>Rscript data/macod_isibalo/load_macod.R</code>), then the province subset (<code>Rscript data/macod_isibalo/build_free_state.R</code>).</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2026 MRC Vital Registration Analysis</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>